# Generated by Django 5.1.6 on 2025-02-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelimages',
            options={'ordering': ['uid']},
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='home.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
